version: "3"
services:
  form:
    image: uxforms/local-formexecutor:15.5.45-dsl.15.16.4
    ports:
      - "${UXFORMS_FORMDEF_PORT}:9000"
      - "${UXFORMS_DEBUG_PORT}:5000"
    volumes:
      - ${UXFORMS_FORMDEF_JAR_DIR}:/opt/docker/formdefinition/formdef
      - file-data:/opt/docker/lib/tmp
    entrypoint:
      bin/formexecutor-local
    command: >
      -DstaticAssetsBaseURL=http://localhost:${UXFORMS_STATICSERVER_PORT}
      -DstaticAssetsBaseServerURL=http://host.docker.internal:${UXFORMS_STATICSERVER_PORT}
      -Djava.security.manager
      -Djava.security.policy==/opt/docker/conf/java.policy
      -Djava.security.properties=/opt/docker/conf/java.security
      -Djava.util.concurrent.ForkJoinPool.common.threadFactory=com.uxforms.formexecutor.SecureForkJoinFactory
      -J-XX:MaxRAM=268435456
      -J-XX:+UseSerialGC
      -jvm-debug ${UXFORMS_DEBUG_PORT}
      -Dformdefinition.classpath.0=/opt/docker/formdefinition/formdef/${UXFORMS_FORM_NAME}_2.11-${UXFORMS_FORM_VERSION}.jar
      -Dfdf.name=${UXFORMS_FORM_FACTORYCLASSNAME}
      -Dfdf.version=1.0-SNAPSHOT
      -DformExecutor.local.formFilesWorkingDir=/opt/docker/lib/tmp
      -DformExecutor.local.fileHostUrl="http://host.docker.internal:${UXFORMS_FILESERVER_PORT}"
      -DformExecutor.uxformsTheme.baseUrl="https://static.uxforms.com/uxforms"

  files:
    image: nginx:1.15.8-alpine
    volumes:
      - file-data:/usr/share/nginx/html
    ports:
      - "${UXFORMS_FILESERVER_PORT}:80"

  theme:
    image: nginx:1.15.8-alpine
    volumes:
      - ${UXFORMS_THEME_DIR}:/usr/share/nginx/html/${UXFORMS_THEME_NAME}
    ports:
      - "${UXFORMS_STATICSERVER_PORT}:80"

volumes:
  file-data:

